name: Publish Python distributions to PyPI

on: push

jobs:
  build-and-test:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
        
      - name: Install make and wget
        run: sudo apt-get install make wget
        
      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
          
      - name: Install docker
        uses: docker-practice/actions-setup-docker@master
        with:
          docker_channel: stable
          docker_version: 19.03

      - name: Install doker-compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Start up docker-compose
        run: | 
          cd deployment
          docker-compose up -d
          sleep 2m
          
      - name: Build and test 
        run: make docker-test

      - name: Publish a Python distribution to PyPI
        if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}