name: Publish Python distributions to PyPI

on:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
        
      - name: Install make and wget
        run: sudo apt-get install make wget
        
      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
          
      - name: Install docker
        uses: docker-practice/actions-setup-docker@master
        with:
          docker_channel: stable
          docker_version: 19.03
          
      - name: Build and test 
        run: make docker-test
        